/**
 * Onboordo API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ErrorResponseMessage } from './errorResponseMessage';


export interface ErrorResponse { 
    /**
     * HTTP status code
     */
    statusCode: number;
    message: ErrorResponseMessage;
    /**
     * Short error type
     */
    error: string;
}

