/**
 * Onboordo API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface SetupStatusResponse {
  /**
   * True if the system requires first-run initialization.
   */
  needsSetup: boolean;
}
