/**
 * Onboordo API
 * API for Onboordo, including first-run setup flow.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ErrorResponseMessage } from './errorResponseMessage';

export interface ErrorResponse {
  /**
   * HTTP status code
   */
  statusCode: number;
  message: ErrorResponseMessage;
  /**
   * Short error type
   */
  error: string;
}
