/**
 * Onboordo API
 * API for Onboordo, including first-run setup flow.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Detailed error message or array of validation errors
 */
/**
 * @type ErrorResponseMessage
 * Detailed error message or array of validation errors
 * @export
 */
export type ErrorResponseMessage = Array<string> | string;

