/**
 * Onboordo API
 * API for Onboordo, including first-run setup flow.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface SetupRequest {
  /**
   * The email address for the initial admin user.
   */
  email: string;
  /**
   * The password for the initial admin user. Must be at least 8 characters.
   */
  password: string;
  /**
   * The name of the initial workspace. Must be at least 3 characters.
   */
  workspaceName: string;
}
