/**
 * Onboordo API
 * API for Onboordo, including first-run setup flow.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Injectable, Optional } from '@nestjs/common';
import { HttpService } from '@nestjs/axios';
import type { AxiosRequestConfig, AxiosResponse } from 'axios';
import { Observable, from, of, switchMap } from 'rxjs';
import { ErrorResponse } from '../model/errorResponse';
import { SetupRequest } from '../model/setupRequest';
import { SetupStatusResponse } from '../model/setupStatusResponse';
import { SetupSuccessResponse } from '../model/setupSuccessResponse';
import { Configuration } from '../configuration';
import { COLLECTION_FORMATS } from '../variables';


@Injectable()
export class SystemService {

    protected basePath = '/api/v1';
    public defaultHeaders: Record<string,string> = {};
    public configuration = new Configuration();
    protected httpClient: HttpService;

    constructor(httpClient: HttpService, @Optional() configuration: Configuration) {
        this.configuration = configuration || this.configuration;
        this.basePath = configuration?.basePath || this.basePath;
        this.httpClient = configuration?.httpClient || httpClient;
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        return consumes.includes(form);
    }

    /**
     * Initialize the system
     * Creates the initial workspace, admin user, and default API key. This endpoint is only available if the system has not been set up yet.
     * @param setupRequest 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param {*} [systemSetupPostOpts.config] Override http request option.
     */
    public systemSetupPost(setupRequest: SetupRequest, systemSetupPostOpts?: { config?: AxiosRequestConfig }): Observable<AxiosResponse<SetupSuccessResponse>>;
    public systemSetupPost(setupRequest: SetupRequest, systemSetupPostOpts?: { config?: AxiosRequestConfig }): Observable<any> {
        if (setupRequest === null || setupRequest === undefined) {
            throw new Error('Required parameter setupRequest was null or undefined when calling systemSetupPost.');
        }

        let headers = {...this.defaultHeaders};

        let accessTokenObservable: Observable<any> = of(null);

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers['Accept'] = httpHeaderAcceptSelected;
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers['Content-Type'] = httpContentTypeSelected;
        }
        return accessTokenObservable.pipe(
            switchMap((accessToken) => {
                if (accessToken) {
                    headers['Authorization'] = `Bearer ${accessToken}`;
                }

                return this.httpClient.post<SetupSuccessResponse>(`${this.basePath}/system/setup`,
                    setupRequest,
                    {
                        withCredentials: this.configuration.withCredentials,
                        ...systemSetupPostOpts?.config,
                        headers: {...headers, ...systemSetupPostOpts?.config?.headers},
                    }
                );
            })
        );
    }
    /**
     * Check if the system requires first-run setup
     * Returns whether the initial workspace, admin user, and default API key have been created.
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param {*} [systemSetupStatusGetOpts.config] Override http request option.
     */
    public systemSetupStatusGet(systemSetupStatusGetOpts?: { config?: AxiosRequestConfig }): Observable<AxiosResponse<SetupStatusResponse>>;
    public systemSetupStatusGet(systemSetupStatusGetOpts?: { config?: AxiosRequestConfig }): Observable<any> {
        let headers = {...this.defaultHeaders};

        let accessTokenObservable: Observable<any> = of(null);

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers['Accept'] = httpHeaderAcceptSelected;
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];
        return accessTokenObservable.pipe(
            switchMap((accessToken) => {
                if (accessToken) {
                    headers['Authorization'] = `Bearer ${accessToken}`;
                }

                return this.httpClient.get<SetupStatusResponse>(`${this.basePath}/system/setup-status`,
                    {
                        withCredentials: this.configuration.withCredentials,
                        ...systemSetupStatusGetOpts?.config,
                        headers: {...headers, ...systemSetupStatusGetOpts?.config?.headers},
                    }
                );
            })
        );
    }
}
